[package]
name = "cipolla"
authors = ["Mark Hähnel <hello@markhaehnel.de>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
arti-client = "0.11.0"
axum = "0.6.20"
hyper = "0.14.27"
lazy_static = "1.4.0"
tokio = { version = "1.34.0", features = ["full"] }
tor-rtcompat = "0.9.5"
tower = "0.4.13"
